// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: proto/quote.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuoteGrabberClient is the client API for QuoteGrabber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoteGrabberClient interface {
	GrabQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteReply, error)
}

type quoteGrabberClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoteGrabberClient(cc grpc.ClientConnInterface) QuoteGrabberClient {
	return &quoteGrabberClient{cc}
}

func (c *quoteGrabberClient) GrabQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteReply, error) {
	out := new(QuoteReply)
	err := c.cc.Invoke(ctx, "/quote.QuoteGrabber/GrabQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteGrabberServer is the server API for QuoteGrabber service.
// All implementations must embed UnimplementedQuoteGrabberServer
// for forward compatibility
type QuoteGrabberServer interface {
	GrabQuote(context.Context, *QuoteRequest) (*QuoteReply, error)
	mustEmbedUnimplementedQuoteGrabberServer()
}

// UnimplementedQuoteGrabberServer must be embedded to have forward compatible implementations.
type UnimplementedQuoteGrabberServer struct {
}

func (UnimplementedQuoteGrabberServer) GrabQuote(context.Context, *QuoteRequest) (*QuoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrabQuote not implemented")
}
func (UnimplementedQuoteGrabberServer) mustEmbedUnimplementedQuoteGrabberServer() {}

// UnsafeQuoteGrabberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoteGrabberServer will
// result in compilation errors.
type UnsafeQuoteGrabberServer interface {
	mustEmbedUnimplementedQuoteGrabberServer()
}

func RegisterQuoteGrabberServer(s grpc.ServiceRegistrar, srv QuoteGrabberServer) {
	s.RegisterService(&QuoteGrabber_ServiceDesc, srv)
}

func _QuoteGrabber_GrabQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteGrabberServer).GrabQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quote.QuoteGrabber/GrabQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteGrabberServer).GrabQuote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuoteGrabber_ServiceDesc is the grpc.ServiceDesc for QuoteGrabber service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuoteGrabber_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quote.QuoteGrabber",
	HandlerType: (*QuoteGrabberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrabQuote",
			Handler:    _QuoteGrabber_GrabQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/quote.proto",
}
